from pathlib import Path
p = Path('README.md')
s = p.read_text(encoding='utf-8')
changes = {
'- Tab/request menus offer rename and duplicate actions. A duplicate is a separate request; save it to its intended collection.': '- **Duplicate tab** in the request menu creates a separate unsaved draft. **Duplicate request** in a collection row\'s menu immediately creates a saved copy beside the original in the same collection/folder, without opening a tab. Rename saved requests from their collection row menu.',
'**Params** and the URL stay synchronized. Repeated keys are supported. Disabling/deleting a parameter changes the URL sent to the server. Variables are supported; query values are URL-encoded.': '**Params** and the URL stay synchronized, including URLs imported from cURL or Postman collections and older saved drafts. Repeated keys, empty values, disabled rows, descriptions, and variable references are retained. Disabling/deleting a parameter changes the URL sent to the server. The URL field preserves imported spelling; editing a parameter keeps readable `@` characters while safely encoding query delimiters. The native request may encode `@` as `%40`; both represent the same value. Explicit disabled rows are excluded even if the imported raw URL contains that key.',
'5. Reopen requests from the tree. Editing keeps a draft; **Save** updates the collection entry.': '5. Reopen requests from the tree. Editing keeps a draft; **Save** updates the collection entry. After saving an imported cURL for the first time, subsequent **Save** clicks update that same entry. **Save as…** deliberately creates another saved request.',
'2. Add a name, value, and optional description. Enable the row. Changes save automatically.': '2. Add a name, value, and optional description. Enable the row. Changes save automatically; **Save** writes the current values to local storage immediately.',
'Environments support rename, activation, export, and confirmed deletion. Globals are workspace-wide; environment values override them.': 'Environments support rename, activation, export, and confirmed deletion. Globals are workspace-wide; environment values override them.\n\nThe gear beside the toolbar\'s environment selector opens **Environment values** without leaving your request. Edit or enable/disable the active environment\'s values and click **Save**; the next request uses them. **Cancel**, Escape, or closing the popup discards its pending edits. With **No environment** selected, the popup edits Globals. Add/remove/rename variables in the full Environments editor. Selecting an environment in the sidebar opens its editor; select it in the toolbar or use **Set active** to use it when sending.\n\nVariable references are colored in URL, field tables, authorization inputs, request bodies, and scripts. Resolved references use the chosen accent; missing/circular references use the error color; dynamic references have a dotted underline. Hover a reference to inspect its current value, source scope, and active environment. Hovering dynamic references describes generation on Send and does not generate a random value or contact a server.',
'Use **Console** in the left sidebar, between **Environments** and **History**, to toggle its dock. It shows request activity, responses/errors, timing, and script logs. Filter entries, expand a run for details, or use its replay action. **Clear console** clears its display without deleting history. It is an activity viewer, not a shell. Details can include credential/payload values.': 'Use **Console** in the left sidebar, between **Environments** and **History**, to toggle its dock. It shows request activity, responses/errors, timing, and script logs. Filter entries, expand a run for details, or use its replay action. **Clear console** clears its display without deleting history. Details can include credential/payload values.\n\nExpand a run to see **Request cURL** and copy the command actually captured during sending, after pre-request scripts, variable substitution, authorization, cookies, and native headers. The final attempt is shown after redirects or authorization challenges. The saved command stays tied to that run across edits and relaunches; viewing it never regenerates tokens, signatures, or random values. A failed connection can still retain the attempted command. Old history created before this update has no native capture and says so. Small binary/multipart bodies up to 2 MB embed captured bytes; larger uploads use local file references and display a replay limitation. Commands above the capture size limit are omitted with an explicit note. Replaying a command with captured credentials uses those original credentials.\n\nEach new run replaces the response editor content, including HTTP 401/403/404 and empty bodies. A connection failure clears the previous body and records the error instead of reusing an earlier response.',
'| Request **Copy as cURL** | Quoted command with current variables resolved. |': '| Workspace **Copy request as cURL** icon below Send | Quoted preview command with current variables resolved. |',
'cURL still uses the existing exporter and **Copy as cURL** remains available for one-click copying.': 'cURL still uses the existing exporter; the **Copy request as cURL** icon below Send remains available for one-click preview copying. Console\'s saved **Request cURL** reflects the actual run, including script/native changes.',
'The top-right question mark opens **About and Help**.': '**About and Help** sits immediately above Settings in the left sidebar.',
'Click the question mark in the top-right corner to open **About and Help**.': 'Click **About and Help** in the left sidebar, above **Settings**, to open it.',
}
for old, new in changes.items():
    assert old in s, old
    s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
